### ISSUE TITLE
Icono indicador de bateria

### ISSUE THREAD

**Issue by cemetary** [fabianalexisinostroza/El-General-Gnome#1]
Hola, Fabián.

Primero que nada, quiero agradecerte por tan genial tema de íconos.

En segundo lugar, tengo una petición que tiene que ver con el ícono del indicador de batería, y a como podés ver en esta toma de pantalla, es demasiado grande y desencaja junto con el resto de íconos (Distro: elementary OS). Bueno, una foto habla mejor que mil palabras: http://imgur.com/iJki7BI

Te agradezco de antemano.

Un abrazo. :-)

**Comment by fabianalexisinostroza** [comment]
Ya te contesté en gnome-look. El problema está corregido (: así que cerraré el Issue
