### ISSUE TITLE
Mimetypes for javascript and json

### ISSUE THREAD

**Issue by mapaiva** [fabianalexisinostroza/El-General-Gnome#2]
First of all, very very congratulations for the icon theme. It's just awesome!!
Taking a most deep look I noticed that the mimetypes for js and json files are equals to java...

![captura de tela de 2015-12-15 08-51-14](https://cloud.githubusercontent.com/assets/8807694/11808711/4f2067a4-a309-11e5-87a0-15ad4434ef1c.png)

Would be nice have these mimes for the theme... :smile: Just a small request.

Thank you
Matheus

**Comment by fabianalexisinostroza** [comment]
Hi (: thanks for use my icons. Now the Github Repo is updated with your request 
![icons 33](https://cloud.githubusercontent.com/assets/14989730/11812104/929fbcf0-a318-11e5-941c-5c9510f01b7d.png)

**Comment by mapaiva** [comment]
Wow great thing!! I will update my local project with these icons. Thank so much :smile:
