### ISSUE TITLE
Icon request: symbolic icon for Redshift

### ISSUE THREAD

**Issue by grvrulz** [fabianalexisinostroza/El-General-Gnome#3]
I'm using the theme on elementary OS, and the panel icon for redshift is a coloured one.
![screenshot from 2015-12-15 23 29 33](https://cloud.githubusercontent.com/assets/1659416/11819028/b5d64656-a383-11e5-803d-8b0c34d7b760.png)

Please make a monochrome icon for redshift.
Thanks

**Comment by fabianalexisinostroza** [comment]
Added icon in Repository may be work now
![icons 34](https://cloud.githubusercontent.com/assets/14989730/11819308/ed0a1904-a33d-11e5-885b-01e1cdfaabd1.png)

**Comment by grvrulz** [comment]
You can add a filled icon and an empty one for different states of redshift. Please see below screenshot for icons in elementaryPlus icon set.

![screenshot from 2015-12-15 23 51 19](https://cloud.githubusercontent.com/assets/1659416/11819599/c2d8996e-a386-11e5-90e0-727b2ad6dc68.png)

**Comment by grvrulz** [comment]
On second thought, maybe an icon without the rays would be better for the 'off' state.

**Comment by fabianalexisinostroza** [comment]
Added now on repository

![Uploading icons 35.png…]()

**Comment by grvrulz** [comment]
Wow man!! You are fast.

Thanks a lot. :D Keep rocking :)
