### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by bil-elmoussaoui** [fabianalexisinostroza/El-General-Gnome#4]
Hello, 
I do love your icon pack. But i have a few of missing icons
-  Builder 
- Feedreader
- Octave

**Comment by fabianalexisinostroza** [comment]
Hi, thanks for use my icons. I the next update i will include your request. Promise

**Comment by kapsule** [comment]
Hi,

I think a really great library. I've seen some icons missing. I indicated to you if you'll be adding in the future.

PAC-Manager
SAP
FortiClient SSL VPN
Synapse
Meld

Thank you.

**Comment by fabianalexisinostroza** [comment]
i will work on it ;)

**Comment by cemetary** [comment]
Hola.

Es el mejor tema de íconos que he podido encontrar. He aquí una lista de programas que me gustaría pudieras agregar:

DraftSight
AZARDI
nomacs
Skype

De antemano, muchas gracias. ;-)
