### ISSUE TITLE
Request: file selection badges in elementary Files

### ISSUE THREAD

**Issue by renearts** [fabianalexisinostroza/El-General-Gnome#7]
When using the (default) single-click option to open files there is currently no selection badge to select a file, one has to guess the area where to click to select while risking unintentionally opening the file. 
(i.e. not quite handy while quickly trying to delete some, erhm, 'private' files which you don't want to open and start playing at that exact moment) ;-)

**Comment by fabianalexisinostroza** [comment]
thanks for use the icons but i don't will update the set for gnome or fix bugs... i will delete the repository in a couple of weeks, but if you want make these corrections, i recommend fork the project and edit yourself.

I prefer be honest to the gnome users, i dont use gnome and recently installed chakra and need the efforts on my liked DE (Plasma)

**Comment by renearts** [comment]
Sad to hear you cannot continue development of this great theme, but understandable IMHO. Just forked it to preserve the theme for myself. Adding the badges (straight copy from the elementary icon set) wasn't too much a hassle fortunately :)
